### ISSUE TITLE
error in coalgen_thinning_hetero()

### ISSUE THREAD

**Issue by JuliaPalacios** [mdkarcher/phylodyn#11]
In line 100, the second while (b>1) {...}, the acceptance probability uses inverse trajectory not trajectory. Replace
```r
   if (runif(1)<=trajectory(E+s,...)/upper)
```
by
```r
   if (runif(1)<=1/(trajectory(E+s,...)*upper))
```

**Comment by mdkarcher** [comment]
I already changed it to
`if (runif(1) <= traj_inv(E+s,...)/upper)`
in response to issue #8
