### ISSUE TITLE
what happened to BNPR?

### ISSUE THREAD

**Issue by JuliaPalacios** [mdkarcher/phylodyn#14]
Hey @mdkarcher 

I wanted to use BNPR as in the vignettes but they not longer exist?

**Comment by JuliaPalacios** [comment]
It seems to be an issue with the installation. I get an error with INLA. I'll keep checking. I see the function in the code

**Comment by JuliaPalacios** [comment]
library(phylodyn)
Error in FUN(X[[i]], ...) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/phylodyn/R/phylodyn.rdb' is corrupt
In addition: Warning messages:
1: In FUN(X[[i]], ...) : restarting interrupted promise evaluation
2: In FUN(X[[i]], ...) : internal error -3 in R_decompress1

**Comment by vnminin** [comment]
Hmm, I've tested BNPR a couple of days ago; everything worked for me. Maybe @mdkarcher made some changes after that...

**Comment by mdkarcher** [comment]
The internet suggests this is the answer:
The internal error -3 often happens when you use install_github to install a package that's currently loaded; try restarting R and running the app again.

**Comment by JuliaPalacios** [comment]
Thanks!!
