### ISSUE TITLE
contributor?

### ISSUE THREAD

**Issue by JuliaPalacios** [mdkarcher/phylodyn#15]
Hi @vnminin and @mdkarcher 

I am wondering if you can add me as a contributor? I would like to receive notifications of commits. Every time I try to use the package, I have re-learn it.

**Comment by vnminin** [comment]
Good point, @JuliaPalacios. @mdkarcher, please also make me an admin so I can't help with similar requests in the future.

**Comment by mdkarcher** [comment]
Hmm, I'm not sure how to help. @JuliaPalacios you are already a collaborator with push privileges--have you checked your notification settings? @vnminin you are a collaborator, too, but I don't see an option in the settings to raise your privileges to admin.

**Comment by vnminin** [comment]
Got it. I got confused github and bitbucket interfaces.
