### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by grd901** [mdkarcher/phylodyn#16]
I'm currently having a problem installing from the most recent version. This code:

```
install_github("mdkarcher/phylodyn")
```

throws the following error:

>Warning in file(filename, "r", encoding = encoding) :
  cannot open file 'C:/Users/grd/AppData/Local/Temp/Rtmp67zn36/devtoolsab030e112e6/mdkarcher-phylodyn-c18d6ce/source/coal_lik_BSMC.R': No such file or directory
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Error : unable to load R code in package 'phylodyn'
ERROR: lazy loading failed for package 'phylodyn'

Installation is successful when installing from a previous version:

```
install_github("mdkarcher/phylodyn", ref="dda35d9")
```

**Comment by JuliaPalacios** [comment]
I'm working on it! But unless you need to model recombination. The previous version should be ok. Thank you for raising the issue.
Julia

**Comment by JuliaPalacios** [comment]
The last version should work now.
Thank you !

**Comment by carolynzy** [comment]
Hi, I'm experiencing the following problem when trying installation:

> 
> install_github("mdkarcher/phylodyn")
Downloading GitHub repo mdkarcher/phylodyn@master
Installing 1 packages: dotCall64
Installing package into ‘C:/Users/carol/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Error: (converted from warning) unable to access index for repository https://www.math.ntnu.no/inla/R/stable/src/contrib:
  cannot open URL 'https://www.math.ntnu.no/inla/R/stable/src/contrib/PACKAGES'
> 
What's going wrong? Thanks for help!

**Comment by mdkarcher** [comment]
It looks like R-INLA changed the URL of their repository. I think I've tracked down all the references and updated them to the new one. Try installing again now.

Also see updated R-INLA installation instructions here: http://www.r-inla.org/download if you were referencing our old README.

**Comment by carolynzy** [comment]
Thanks! It's  working now.
