### ISSUE TITLE
INLA

### ISSUE THREAD

**Issue by JuliaPalacios** [mdkarcher/phylodyn#19]
Hi @mdkarcher ,

Maybe we need to add this in the instructions?
 install.packages("INLA", repos="https://www.math.ntnu.no/inla/R/stable")

The package needs to have INLA installed for installation. Alternatively, can we change that?

**Comment by mdkarcher** [comment]
Good call! I thought they got INLA into CRAN at some point, but the current download instructions for INLA do require the repos argument.
