### ISSUE TITLE
travis errors

### ISSUE THREAD

**Issue by JuliaPalacios** [mdkarcher/phylodyn#20]
Hi @mdkarcher 

There is a Travis error with LongPhyloinfer.Rmd. Can you please fix it? It is not allowing me to build with my new code and I want to test everything works for the new vignette "simulations.Rmd".

Thanks

**Comment by mdkarcher** [comment]
I'm still working on this. I can't replicate it locally, so I can't access the stack trace.

**Comment by mdkarcher** [comment]
I found and solved the problem.
