### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by mdkarcher** [mdkarcher/phylodyn#22]
@JuliaPalacios Would you check some of these functions for global variables? The package check returns this:

checking R code for possible problems ... NOTE
coal_loglik_smc: no visible binding for global variable ‘n’
get.data: no visible binding for global variable ‘tol’
get_F_values: no visible binding for global variable ‘C2’
get_F_values: no visible binding for global variable ‘n’
number.thinned: no visible binding for global variable ‘l’
write.xml: no visible global function definition for ‘str_split_fixed’
write.xml: no visible global function definition for ‘write.tree’

**Comment by vnminin** [comment]
Is this resolved now?

**Comment by mdkarcher** [comment]
Yes, it's resolved
