### ISSUE TITLE
Variable error

### ISSUE THREAD

**Issue by mdkarcher** [mdkarcher/phylodyn#24]
When I knit LocalGenealogies.Rmd, I get an error saying "Error: object 'n' not found"

It looks like there are still a couple references to a variable "n" without a definition in coal_lik_BSMC.R at lines 157 and 158:

```
myF.out<-n-init$C[j,((i+1):m.1)]+1
myF<-init$Fl[[j]][,(n-myF.in+1)][myF.out]
```

**Comment by vnminin** [comment]
Is this resolved now?

**Comment by mdkarcher** [comment]
Yes, it's resolved
