### ISSUE TITLE
Estimate growth rate and likelihood for coalescent exponential

### ISSUE THREAD

**Issue by LeoFeatherstone** [mdkarcher/phylodyn#31]
I am looking to estimate population growth rate and the likelihood thereof for a coalescent exponential model, however I am having trouble deciphering which function does this by looking at the code. Could you please direct me to the function I should use?

Thanks,
Leo

**Comment by vnminin** [comment]
Hi Leo,

Looks to me like the last function in [https://github.com/mdkarcher/phylodyn/blob/master/R/simple_models.R](https://github.com/mdkarcher/phylodyn/blob/master/R/simple_models.R) is what you are looking for.

@mdkarcher will correct me if I am wrong.

**Comment by LeoFeatherstone** [comment]
Hi Vladimir,
Thank you kindly for that. For me that function is returning two negative values - can I assume these are the negative of the growth rate and the log-likelihood respectively?

Thanks,
Leo

**Comment by vnminin** [comment]
My understanding of the code is that these two values are estimates of beta0 and beta1, which are parameters of the exponential growth curve f(t) = exp(beta0 + beta1t).
