### ISSUE TITLE
Install Error when running install_github("mdkarcher/phylodyn")

### ISSUE THREAD

**Issue by Volcanix280** [mdkarcher/phylodyn#32]
R - 3.6.1 on Linux, installed on a a previously cleaned library. When I run the command above I get:

The downloaded source packages are in
        ‘/tmp/RtmpWgaiCI/downloaded_packages’
✔  checking for file ‘/tmp/RtmpWgaiCI/remotes2352021d14f8a/mdkarcher-phylodyn-6bb23ab/DESCRIPTION’ (433ms)
─  preparing ‘phylodyn’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘phylodyn_0.9.02.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'

Installing package into ‘$HOME/R-3.6.1/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘phylodyn’ ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) :
  object 'infer_coal_samp' not found
Error: unable to load R code in package ‘phylodyn’
Execution halted
ERROR: lazy loading failed for package ‘phylodyn’
* removing ‘$HOME/R-3.6.1/library/phylodyn’
* restoring previous ‘$HOME/R-3.6.1/library/phylodyn’
Error: Failed to install 'phylodyn' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpWgaiCI/file23520180740ce/phylodyn_0.9.02.tar.gz’ had non-zero exit status

**Comment by damonbayer** [comment]
This issue was introduced in the most recent commit. Going back to https://github.com/mdkarcher/phylodyn/tree/e4bc78ddb8efb8a82c8d1e49bcf36dacf3912212 should work.

`remotes::install_github("mdkarcher/phylodyn", ref = "e4bc78ddb8efb8a82c8d1e49bcf36dacf3912212")`

**Comment by vnminin** [comment]
Closing this, but note the vignettes do not compile yet.
