### ISSUE TITLE
change in inla formula

### ISSUE THREAD

**Issue by JuliaPalacios** [mdkarcher/phylodyn#4]
Hi Mike,

The R-INLA package disabled the "si" option in the INLA formula. In our case it was set to FALSE so the only update you need to do is the following:

in all calculate.moller.hetero functions
replace:
formula <- y ~ -1 + f(time, model = "rw1", hyper = list(prec = list(param = c(alpha, 
        beta))), constr = FALSE, si = FALSE)
by:

formula <- y ~ -1 + f(time, model = "rw1", hyper = list(prec = list(param = c(alpha, 
        beta))), constr = FALSE)

I don't know if I do the change it would mess up your package. 

~Julia

**Comment by mdkarcher** [comment]
I made the necessary changes and pushed the fix. Thanks for the heads-up, Julia!
